apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.MongoSecret }}
    namespace: {{ .Values.Namespace }}
type: Opaque
data:
    mongo-root-username: {{  randAlpha 10 | b64enc | quote  }}
    mongo-root-password: {{  randAlphaNum 32 | b64enc | quote  }}
