apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  allocateLoadBalancerNodePorts: false
  ports:
    - targetPort: 3000
      port: 80
  selector:
    app: frontend
  type: LoadBalancer