resource "google_service_account" "service_account" {
  for_each     = var.service_accounts
  account_id   = each.value.account_id
  display_name = "${var.name_prefix}-${each.value.name}"

}
resource "google_project_iam_custom_role" "custom_roles" {
  for_each    = var.service_accounts
  role_id     = each.value.role_id
  title       = "${var.name_prefix}-${each.value.name}"
  description = "this role is autogenerated and maintained by terraform don't use it "
  permissions = each.value.permissions

}

data "google_client_config" "this" {

}

resource "google_project_iam_binding" "bindings" {
  for_each = var.service_accounts
  role     = google_project_iam_custom_role.custom_roles[each.key].id
  project  = data.google_client_config.this.project
  members  = [google_service_account.service_account[each.key].member, ]
}